#profile
spring:
  profiles:
    active: dev
  devtools:
    remote:
      restart:
        enabled: true
#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hulihuli.dao